### PR TITLE
fix decode problem of videos with no `tags` field  (issue #21)

### LINKED ISSUE #21: can not get video list resources with no tags
Some Youtube videos has no `tags` filed when user upload that videos. For example [this one](https://youtu.be/AmB-d_gIvoM). This kind of video will suffer from decode error when, for example, developer try to make requests like this:
`let request = VideoListRequest(part: [Part.VideoList.snippet], filter: Filter.VideoList.id("AmB-d_gIvoM"))`

error message:
`keyNotFound(CodingKeys(stringValue: "tags", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "items", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "snippet", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"tags\", intValue: nil) (\"tags\").", underlyingError: nil))
`

It actually very easy to fix, just make const `tags` at `Snippet.swift` line 18 as optional:
`public let tags: [String]? `

I add a little bit more error handling in ApiSession.swift although it is far from adequate.

Default implementation of methods in `YTSwiftyPlayerDelegate` should be public in order to make delegate methods to be optional:
```
public extension YTSwiftyPlayerDelegate {
...
}
```

Will submit a pull-request soon.

### PR DESCRIPTION
**Pull request by ctwdtw**
1. make const `tags` at Snippet.swift line 18 as optional
2. add status code guard clause in ApiSession.swift
3. make Default implementation of YTSwiftyPlayerDelegate methods public so that they are optional

Closes #21

### CODE REVIEW

File: YoutubeKit/API/ApiSession.swift [hunk 1]
```diff
@@ -21,31 +21,83 @@ public class ApiSession {
             
             // If the dataTask error is occured.
             if let error = error {
-                closure(.failed(ResponseError.unexpectedResponse(error)))
+                DispatchQueue.main.async {
```
Comment (rinov) [inline YoutubeKit/API/ApiSession.swift]: Why do you add `DispatchQueue.main.async`?

File: YoutubeKit/Common/Result.swift [hunk 2]
```diff
@@ -10,4 +10,21 @@ import Foundation
 public enum Result<T, E> {
     case success(T)
     case failed(E)
+    public var value: T? {
```
Comment (rinov) [inline YoutubeKit/Common/Result.swift]: Is this diff need for this PR?

Comment (ctwdtw) [reply YoutubeKit/Common/Result.swift]: no, this is not needed for this PR. I added this because instead of using `switch statement` I want to use syntax like this:
```
ApiSession.shared.send(request, closure: { (result) in
        if let value = result.value {
          print(value)
          
        } else if let error = result.error {
          print(error)
          
        }
        
      })
```
un...sorry I am new to open source project, next time I will try to see if I can separate things more clearly in commits. 😅

File: YoutubeKit/API/ApiSession.swift (hunk 1 above)
Comment (ctwdtw) [reply YoutubeKit/API/ApiSession.swift]: I added `DispatchQueue.main.async` because I heard that It is a good practice to make the `completion block` (closure) of an async function to run on the `main queue` so that the caller will not get confused  easily. For example, in `Alamofire`, they make their `completionHandler` run on the `main queue` by default, but the caller can specify their own if they want. See this code snippet in line 106 of `ResponseSerialization.swift` in `Alamofire`'s source: 
```
extension DataRequest {
    /// Adds a handler to be called once the request has finished.
    ///
    /// - parameter queue:             The queue on which the completion handler is dispatched.
    /// - parameter completionHandler: The code to be executed once the request has finished.
    ///
    /// - returns: The request.
    @discardableResult
    public func response(queue: DispatchQueue? = nil, completionHandler: @escaping (DefaultDataResponse) -> Void) -> Self {
        delegate.queue.addOperation {
            (queue ?? DispatchQueue.main).async {
                var dataResponse = DefaultDataResponse(
                    request: self.request,
                    response: self.response,
                    data: self.delegate.data,
                    error: self.delegate.error,
                    timeline: self.timeline
                )

                dataResponse.add(self.delegate.metrics)

                completionHandler(dataResponse)
            }
        }

        return self
    }
```
Please let me know your experience and opinion, I am happy to learn. 😄

File: YoutubeKit/Common/Result.swift (hunk 2 above)
Comment (rinov) [reply YoutubeKit/Common/Result.swift]: This property is convenience, but a pull request should be minimum changes or separate if needed for review costs. (but it's ok is this time 👍)
